name: Auction
main: cc.isotopestudio.Auction.Auction

author: Mars
description: Auctions
website: http://isotopestudio.cc
version: 1.2.3.1
commands:
  Auction:
    description: Auction command
    usage: /<command> - Get Information
    aliases: paimai